export const LOGIN_PAGE_HEADING: String = "login"
export const USERNAME_NULL: String = "Please enter your User name"
export const USERNAME_INVALID: String = "Must be 3 characters long / more"
export const PASSWORD_NULL: String = "Password not entered"
export const EMAIL_INVALID:string = "Email invalid"